### ISSUE TITLE
getting : Could't authenticate you msg

### ISSUE THREAD

**Issue by liccy-fuentes** [jeremypeter/grunt-litmus#1]
In my gruntfile.js I included my username + password, but when i try to run my task I get a [Could't authenticate you]. 

I'm using the same username + password that I use to login into litmus.

**Comment by liccy-fuentes** [comment]
never mind\* Is not an issue.

**Comment by Sawtaytoes** [comment]
Why isn't it an issue? I'm having the same problem myself and have not figured out a fix yet.

**Comment by jeremypeter** [comment]
@Saturn2888  What error is it giving you?

**Comment by Sawtaytoes** [comment]
It's telling me this:

```
X-RACK-CACHE: invalidate, pass

Could't authenticate you
Fatal error: 401 Unauthorized
```

**Comment by jeremypeter** [comment]
The only way I can replicate the issue is if I use the wrong **username** and **password**. 
I've used my email address and my company name as the **username** along with their respected passwords and didn't get any errors. 

@liccy-fuentes perhaps you can chime in and tell us what was causing the issue for you at first and how you resolved it.

**Comment by Sawtaytoes** [comment]
Maybe my URL is wrong. When I login to my account, it shows me `https://litmus.com/tests`.

You noted using `https://yourcompany.litmus.com` in the documentation. Where are you getting the `yourcompany` subdomain from?

**Comment by Sawtaytoes** [comment]
Of course, now I get it working. Under my profile, I noticed a text field: `Subdomain for API`. This is different than what I thought it would be.

**Comment by jeremypeter** [comment]
Awesome! I'll put that information in the documentation

**Comment by jeremypeter** [comment]
Documentation added: https://github.com/jeremypeter/grunt-litmus#optionsurl

**Comment by dnnsldr** [comment]
I am having the same issue. I can log into my account with the username and password. I have verified my "Subdomain for API" inside my profile. But each time I run my grunt task I get an error:

Could't authenticate you
Fatal error: 401 Unauthorized

Here is a screenshot of my terminal after running the tast:
![screen shot 2014-10-01 at 4 26 46 pm](https://cloud.githubusercontent.com/assets/224033/4484937/7be79fc4-49c2-11e4-99f7-962293207b16.png)

I am not sure what is causing this. I am only testing on two clients: iphone5 and chromegmailnew because they usually don't have issues on the litmus site being down.

The URL that I am using in my grunt options is: https://mysubdomainAPIname.litmus.com

**Comment by jeremypeter** [comment]
@dnnsldr If you go to the url in the browser, are you able to login with your username and pass?

**Comment by dnnsldr** [comment]
Yes I can. Of course it redirects to https://riester.litmus.com/sessions/new
